telegram:
  auth:
    token: TELEGRAM_BOT_TOKEN_HERE
  useFirstNameInsteadOfUsername: false
  commaAfterSenderName: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  auth:
    token: DISCORD_BOT_TOKEN_HERE
  skipOldMessages: true
bridges:
- name: Default bridge
  telegram:
    chatId: TELEGRAM_CHAT_ID
    relayJoinMessages: true
    relayLeaveMessages: true
  discord:
    serverId: 'DISCORD_SERVER_ID'         # The ID must be wrapped in single quotes. Example: '244791815503347712'
    channelId: 'DISCORD_CHANNEL_ID'       # The ID must be wrapped in single quotes. Example: '244791815503347712'
    relayJoinMessages: true
    relayLeaveMessages: true
debug: false
